[PROTOCOLS]
Protocols SPA = [
	{"tag": "section", "text": "Tools", "openItem": "True", "children": [
		{"tag": "protocol_group", "text": "Greetings", "openItem": "False", "children": [
		    {"tag": "protocol", "value": "ReinventPrefixHelloWorld", "text": "Hello world"}
        ]},

        {"tag": "protocol_group", "text": "Reinvent", "openItem": "True", "children": [
            {"tag": "protocol", "value": "ReinventTransferLearning", "text": "Transfer Learning"},
            {"tag": "protocol", "value": "ReinventStagedLearning", "text": "Staged Learning"},
            {"tag": "protocol", "value": "ReinventSampling", "text": "Sampling"}
        ]}
	]}
 ]