[PROTOCOLS]
Virtual Screening = [
    {"tag": "section", "text": "Lead optimization", "openItem": "True", "children": [
        {"tag": "protocol", "value": "ReinventTransferLearning", "text": "default"},
        {"tag": "protocol", "value": "ReinventStagedLearning",   "text": "default"},
        {"tag": "protocol", "value": "ReinventSampling",         "text": "default"}
    ]}
 ]
